---
- hosts: all
  gather_facts: true
  remote_user: root
  become: yes
  tasks:

  - name: Generate MD5 hashed password
    expect:
        chdir: /var/lib/rundeck/bootstrap
        command: java -jar rundeck-3.1.2-20190927.war --encryptpwd Jetty
        responses:
            'Username \(Optional, but necessary for Crypt encoding\)': "{{ rd_admin_user }}"
            '\*Value To Encrypt \(The text you want to encrypt\)': "{{ rd_admin_pw }}"
        echo: yes
    register: jetty_output
    become: yes
    become_user: rundeck

  - debug:
        var: jetty_output.stdout_lines|string|regex_search('MD5:[a-zA-Z0-9]{32}')


  


