---
- name: Install Rundeck
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:

    - name: Add EPEL Repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Add Postgres Repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: Add Rundeck Repo
      yum:
        name: https://repo.rundeck.org/latest.rpm
        state: present

    - name: Package installation
      yum:
        name:
        - java-1.8.0-openjdk
        - rundeck
        - rundeck-cli
        - epel-release
        - postgresql10-server
        - python-psycopg2
        state: present
    
    - name: PostgresQL | Init server
      command: /usr/pgsql-10/bin/postgresql-10-setup initdb
      ignore_errors: yes

    - name: PostgreSQL | wait for server to init
      command: sleep 5

    - template:
        src: templates/psql/pg_hba.conf.j2
        dest: /var/lib/pgsql/10/data/pg_hba.conf
        owner: postgres
        group: postgres
        mode: 0700

    - name: PostgreSQL | Start service
      service:
        name: postgresql-10.service
        enabled: yes
        state: restarted

    - name: PostgreSQL | Create Rundeck Database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "{{ rd_db_name }}"
    
    - name: PostgreSQL | Create Rundeck user
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ rd_db_user }}"
        password: "{{ rd_db_password }}"

    - name: PostgreSQL | Grant rundeck user ALL on rundeck database
      become: true
      become_user: postgres
      postgresql_privs:
        db: postgres
        privs: ALL
        type: database
        obj: "{{ rd_db_name }}"
        role: "{{ rd_db_user }}"

    - template:
        src: templates/rundeck/framework.properties.j2
        dest: /etc/rundeck/framework.properties
        owner: rundeck
        group: rundeck
        mode: 0640
        backup: yes

    - template:
        src: templates/rundeck/rundeck-config.properties.j2
        dest: /etc/rundeck/rundeck-config.properties
        owner: rundeck
        group: rundeck
        mode: 0640
        backup: yes

    - template:
        src: templates/rundeck/realm.properties.j2
        dest: /etc/rundeck/realm.properties
        owner: rundeck
        group: rundeck
        mode: 0640
        backup: yes

    - name: Install AWS EC2 Nodes rundeck plugin
      get_url:
        url: https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases/download/v1.5.12/rundeck-ec2-nodes-plugin-1.5.12.jar
        dest: /var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.12.jar
        mode: 0644
      become: true
      become_user: rundeck

    - name: Start Rundeck
      service:
        name: rundeckd
        enabled: yes
        state: restarted
    
    - name: Allow Rundeck through Firewall
      firewalld:
        port: 4440/tcp
        permanent: true
        state: enabled

    - name: Bounce firewalld
      command: firewall-cmd --reload
