---

    - name: Package installation
      yum:
        name:
          - monit
        state: present

    - name: Copy monit files
      copy:
        src: "{{ item }}"
        dest: /etc/monit.d/
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - ../files/*

    - name: Start monit
      service:
        name: monit
        enabled: yes
        state: restarted
