---

    - name: Create Project
      shell: source /var/lib/rundeck/.bash_profile && rd projects create -p "{{ rd_project_name }}"
      become: true
      become_user: rundeck
      args:
        executable: /bin/bash

    - name: Copy Rundeck project config
      template:
        src: config.properties.j2
        dest: /tmp/config.properties
        owner: rundeck
        group: rundeck
        mode: '0755'

    - name: Configure project
      shell: source /var/lib/rundeck/.bash_profile && rd projects configure set -p "{{ rd_project_name }}" -F properties -f /tmp/config.properties

    - name: Remove job config file
      file:
        path: /tmp/config.properties
        state: absent

    - name: Create temporary jobs folder
      file:
        path: /tmp/rd_jobs
        state: directory
        owner: rundeck
        group: rundeck
        mode: '0777'

    - name: Copy jobs to server
      copy:
        src: "{{ item }}"
        dest: /tmp/rd_jobs/
        owner: rundeck
        group: rundeck
        mode: '0777'
      with_fileglob:
        - ../files/*.yaml

    - name: Find jobs in server directory
      shell: find /tmp/rd_jobs/ -type f -name *.yaml
      register: rundeck_jobs

    - name: Import jobs to Rundeck Project
      shell: source /var/lib/rundeck/.bash_profile && rd jobs load -f "{{ item }}" -F yaml -p "{{ rd_project_name }}" -r
      become: true
      become_user: rundeck
      args:
        executable: /bin/bash
      with_items: "{{ rundeck_jobs.stdout_lines }}"

    - name: Clean up after Rundeck jobs import
      file:
        path: /tmp/rd_jobs/
        state: absent
