- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 0a04898c-54b9-48ea-be3f-ff2e9326ea03
  loglevel: INFO
  name: MONIT - Start Processes
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ''
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        #sudo mount -a
        #sleep 5s
        #sudo monit monitor all

        COUNTER=1

        while true; do
                CHECK=$(sudo monit -B summary|egrep 'start|Initializing|exist')

                if [ "$CHECK" == "" ]; then
                        echo "SUCCESS"
                        break
                else
                        if [[ $COUNTER == 30 ]]; then
                                echo ERROR: services are taking too long to shut down. 1>&2
                                exit 1
                        else
                        let COUNTER=COUNTER+1
                        fi
                fi

                sleep 10
        done
    keepgoing: false
    strategy: node-first
  uuid: 0a04898c-54b9-48ea-be3f-ff2e9326ea03
